"""Generates src/shared/RoadCarve.luau: for every ModularRoads piece the road tiler
places, a few rectangles covering the piece's carriageway + paving footprint (not the
grass verge), shrunk by ERODE studs. RoadTiler clears the terrain inside them so the
terrain grass cannot poke through the asphalt and tucked junction arms are not buried.

Coordinates are the piece's bounding-box-centre frame in Studio, unscaled:
studio (x, z) = (-glb x, -glb z)  (checked against part offsets in Studio 2026-09-20).

Run: python tools/kit/make_road_carve.py
"""
import json, struct, os
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GLB = os.path.join(ROOT, "assets", "kit", "_export", "glb")
OUT = os.path.join(ROOT, "src", "shared", "RoadCarve.luau")
PREFIX = "UKSP__ModularRoads__"
PIECES = ["Straight", "StraightYellowLines", "Crossroads", "CrossroadsYellowLines", "TJunctionRight", "TJunctionRightYellowLines",
          "DegreeLeft2", "DegreeLeft90YellowLines", "DegreeRight", "DegreeRight90YellowLines",
          "DegreeLeft45Degree", "DegreeLeft45DegreeYellowLines", "DegreeRight45Degree", "DegreeRight45DegreeYellowLines",
          "CulDeSac", "CulDeSacYellowLines"]
CELL = 2.0   # raster cell, studs
ERODE = 1    # cells taken off every edge that faces the verge
SOLID = {"RoadShader", "PavingShader", "YellowLinesShader"}

def load(path):
    f = open(path, "rb"); f.read(12)
    clen, _ = struct.unpack("<II", f.read(8)); js = json.loads(f.read(clen))
    blen, _ = struct.unpack("<II", f.read(8)); blob = f.read(blen)
    def acc(i):
        a = js["accessors"][i]; bv = js["bufferViews"][a["bufferView"]]
        n = {"VEC2": 2, "VEC3": 3, "SCALAR": 1}[a["type"]]
        dt = {5126: np.float32, 5123: np.uint16, 5125: np.uint32, 5121: np.uint8}[a["componentType"]]
        off = bv.get("byteOffset", 0) + a.get("byteOffset", 0)
        return np.frombuffer(blob, dtype=dt, count=a["count"] * n, offset=off).reshape(-1, n)
    tris, lo, hi = [], None, None
    for m in js["meshes"]:
        for pr in m["primitives"]:
            pos = acc(pr["attributes"]["POSITION"]).astype(np.float64)
            xz = np.stack([-pos[:, 0], -pos[:, 2]], axis=1)
            lo = xz.min(0) if lo is None else np.minimum(lo, xz.min(0))
            hi = xz.max(0) if hi is None else np.maximum(hi, xz.max(0))
            if js["materials"][pr["material"]]["name"] in SOLID:
                idx = acc(pr["indices"]).reshape(-1, 3)
                tris.append(xz[idx])
    return np.concatenate(tris), lo, hi

def raster(tris, lo, hi):
    centre = (lo + hi) / 2
    nx = int(np.ceil((hi[0] - lo[0]) / CELL)); nz = int(np.ceil((hi[1] - lo[1]) / CELL))
    xs = lo[0] + (np.arange(nx) + 0.5) * CELL; zs = lo[1] + (np.arange(nz) + 0.5) * CELL
    gx, gz = np.meshgrid(xs, zs, indexing="ij")
    grid = np.zeros((nx, nz), bool)
    for t in tris:
        (x0, z0), (x1, z1), (x2, z2) = t
        d = (z1 - z2) * (x0 - x2) + (x2 - x1) * (z0 - z2)
        if abs(d) < 1e-9:
            continue
        i0 = max(0, int((min(x0, x1, x2) - lo[0]) / CELL) - 1); i1 = min(nx, int((max(x0, x1, x2) - lo[0]) / CELL) + 2)
        k0 = max(0, int((min(z0, z1, z2) - lo[1]) / CELL) - 1); k1 = min(nz, int((max(z0, z1, z2) - lo[1]) / CELL) + 2)
        px = gx[i0:i1, k0:k1]; pz = gz[i0:i1, k0:k1]
        a = ((z1 - z2) * (px - x2) + (x2 - x1) * (pz - z2)) / d
        b = ((z2 - z0) * (px - x2) + (x0 - x2) * (pz - z2)) / d
        grid[i0:i1, k0:k1] |= (a >= -1e-6) & (b >= -1e-6) & (a + b <= 1 + 1e-6)
    return grid, centre, lo

def erode(grid):
    # a cell survives if its 8 neighbours are solid; cells on the piece's own bbox
    # edge (a connection mouth) count the outside as solid so mouths stay open
    g = np.pad(grid, 1, mode="edge")
    out = grid.copy()
    for di in (-1, 0, 1):
        for dk in (-1, 0, 1):
            out &= g[1 + di:g.shape[0] - 1 + di, 1 + dk:g.shape[1] - 1 + dk]
    return out

def rects(grid):
    grid = grid.copy(); out = []
    nx, nz = grid.shape
    for i in range(nx):
        for k in range(nz):
            if not grid[i, k]:
                continue
            k1 = k
            while k1 + 1 < nz and grid[i, k1 + 1]:
                k1 += 1
            i1 = i
            while i1 + 1 < nx and grid[i1 + 1, k:k1 + 1].all():
                i1 += 1
            grid[i:i1 + 1, k:k1 + 1] = False
            out.append((i, i1, k, k1))
    return out

lines = ["--!strict",
         "-- GENERATED by tools/kit/make_road_carve.py from the kit GLBs. Do not edit by hand.",
         "-- Per ModularRoads piece: rectangles { centreX, centreZ, sizeX, sizeZ } covering its",
         "-- carriageway + paving (not the verge), in the piece's bbox-centre frame, unscaled.",
         "-- RoadTiler clears the terrain inside them.", "",
         "local RoadCarve: { [string]: { { number } } } = {"]
for name in PIECES:
    tris, lo, hi = load(os.path.join(GLB, PREFIX + name + ".glb"))
    grid, centre, lo = raster(tris, lo, hi)
    for _ in range(ERODE):
        grid = erode(grid)
    rs = rects(grid)
    lines.append('\t["%s%s"] = {' % (PREFIX, name))
    for (i, i1, k, k1) in rs:
        cx = lo[0] + (i + i1 + 1) / 2 * CELL - centre[0]; cz = lo[1] + (k + k1 + 1) / 2 * CELL - centre[1]
        lines.append("\t\t{ %.1f, %.1f, %.1f, %.1f }," % (cx, cz, (i1 - i + 1) * CELL, (k1 - k + 1) * CELL))
    lines.append("\t},")
    print(name, len(rs), "rects, cells", int(grid.sum()))
lines += ["}", "", "return RoadCarve", ""]
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
