"""Upload the crest-builder layers (tools/make_crest_parts.py) and generate their Luau id table.

    python tools/upload_crest_parts.py

Reads the Open Cloud key from ROBLOX_API_KEY or the gitignored .roblox_api_key.
Ids are recorded in assets/ui/crest/asset_ids.json, so a re-run only uploads
new or missing layers. It then writes src/shared/CrestImages.luau.
Re-running make_crest_parts.py does not change a recorded id: delete the entry
from asset_ids.json to re-upload an edited layer.
"""
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from upload_kit import upload_one  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = os.path.join(ROOT, "assets", "ui", "crest", "parts")
IDS = os.path.join(ROOT, "assets", "ui", "crest", "asset_ids.json")
LUAU = os.path.join(ROOT, "src", "shared", "CrestImages.luau")
USER = "74667306"


def main():
    key = os.environ.get("ROBLOX_API_KEY")
    if not key:
        with open(os.path.join(ROOT, ".roblox_api_key")) as f:
            key = f.read().strip()
    ids = json.load(open(IDS)) if os.path.exists(IDS) else {}
    for name in sorted(os.listdir(PARTS)):
        stem = os.path.splitext(name)[0]
        if not name.endswith(".png") or stem in ids:
            continue
        asset_id, err = upload_one(os.path.join(PARTS, name), key, USER, "FCT crest " + stem, "Image", "image/png")
        if err:
            print("FAIL", name, err)
            continue
        ids[stem] = int(asset_id)
        json.dump(ids, open(IDS, "w"), indent=1, sort_keys=True)
        print("ok", stem, asset_id)
        time.sleep(1)

    lines = [
        "--!strict",
        "-- GENERATED by tools/upload_crest_parts.py -- do not edit by hand.",
        "-- Crest-builder layers (assets/ui/crest/parts/): white art, tinted in game by ClubCrest.",
        "return {",
    ]
    lines += [f'\t["{k}"] = {v},' for k, v in sorted(ids.items())]
    lines.append("}")
    with open(LUAU, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(ids)} ids -> {LUAU}")


if __name__ == "__main__":
    main()
